# Generated by Django 5.2.17 on 2026-09-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='biz_type',
            field=models.CharField(choices=[('purchase', '收购入库'), ('transfer_in', '调拨入仓'), ('return', '退货入库'), ('sale', '销售出库'), ('transfer_out', '调出出仓'), ('loss', '损耗出库'), ('process', '加工出库'), ('adjust_gain', '盘盈入库'), ('adjust_loss', '盘亏出库')], max_length=20, verbose_name='业务类型'),
        ),
    ]
