# Generated by Django 5.2.17 on 2026-09-14 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_alter_stockrecord_biz_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fumigationtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fumigations', to=settings.AUTH_USER_MODEL, verbose_name='安排人'),
        ),
        migrations.AddField(
            model_name='grainbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='granary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_granaries', to=settings.AUTH_USER_MODEL, verbose_name='建档人'),
        ),
        migrations.AddField(
            model_name='monitorrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monitors', to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_records', to=settings.AUTH_USER_MODEL, verbose_name='制单人'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stocktakes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=30, verbose_name='操作人姓名')),
                ('action', models.CharField(choices=[('login', '登录'), ('login_fail', '登录失败'), ('logout', '登出'), ('create', '新增'), ('update', '修改'), ('delete', '删除'), ('stock_in', '入库'), ('stock_out', '出库'), ('fumigation_advance', '熏蒸状态推进'), ('stocktake_generate', '生成盘点明细'), ('stocktake_adjust', '盘点调账')], max_length=30, verbose_name='动作')),
                ('module', models.CharField(max_length=30, verbose_name='业务模块')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='操作对象')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'depot_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '系统管理员'), ('director', '库管主任'), ('keeper', '保管员'), ('viewer', '只读用户')], default='viewer', max_length=20, verbose_name='岗位角色')),
                ('display_name', models.CharField(blank=True, max_length=30, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('granaries', models.ManyToManyField(blank=True, related_name='keepers', to='depot.granary', verbose_name='管辖仓房')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='系统账号')),
            ],
            options={
                'verbose_name': '用户岗位',
                'verbose_name_plural': '用户岗位',
                'db_table': 'depot_user_profile',
            },
        ),
    ]
