# Generated by Django 5.2.17 on 2026-09-14 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0003_fumigationtask_created_by_grainbatch_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='is_void',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否作废'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='void_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='作废原因'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作废时间'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_stock_records', to=settings.AUTH_USER_MODEL, verbose_name='作废人'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='action',
            field=models.CharField(choices=[('login', '登录'), ('login_fail', '登录失败'), ('logout', '登出'), ('create', '新增'), ('update', '修改'), ('delete', '删除'), ('stock_in', '入库'), ('stock_out', '出库'), ('stock_correct', '单据更正'), ('stock_void', '单据作废'), ('fumigation_advance', '熏蒸状态推进'), ('stocktake_generate', '生成盘点明细'), ('stocktake_adjust', '盘点调账')], max_length=30, verbose_name='动作'),
        ),
    ]
